# Custom Civilian Vehicles
- megaram				-- Dodge Ram Monster							-- Off-Road			-- $
- rancherxlextreme		-- Rancher XL Monster							-- Off-Road			-- $
- sandkinghd			-- Sandking HD Monster							-- Off-Road			-- $
- vapidlow				-- Sandking Lowrider							-- Muscle			-- $
- caracarase			-- CaraCara Special Edition						-- Off-Road			-- $
- huraperfospy			-- 2019 Lamborghini Huracan Performance Spyder	-- Super			-- $
- vantage				-- 2019 Aston Martin Vantage					-- Sports			-- $
- camry18				-- 2018 Toyota Camry XSE						-- Sedan			-- $
- fpino					-- 2018 Ferrari Portofino						-- Super			-- $
- malibu				-- 2018 Chevrolet Malibu						-- Sedan			-- $
- raptor2017			-- 2017 Ford Raptor								-- Off-Road			-- $
- cczl					-- 2017 Chevy Camaro ZL1						-- Sports			-- $
- mlnovitec				-- 2017 Maserati Levante Novitec				-- SUV				-- $
- gtr					-- 2017 Nissan GTR								-- Sports			-- $
- urus					-- 2016 Bentley Bentayga						-- SUV				-- $
- centenario			-- 2016 Lamborghini Centenario LP770			-- Super			-- $
